version: "3.3"

networks:
  net:
    driver: overlay
    attachable: true

configs:
  json-file:
    file: ./json-server/json/db.json

services:

  json-server:
    image: cquan808/docker-json-server:latest
    ports:
      - "5000:3000"
    networks:
      - net
    configs:
      - source: json-file
        target: json-server/json/db.json
    deploy:
      mode: replicated
      replicas: 1
#     placement:
#       constraints:
#         - node.labels.project == epicProject
#         - node.role == manager
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 10
        window: 120s